export const galleryCategories = [
  "Wedding",
  "Birthday",
  "Party",
  "Reception",
  "Mandap",
  "Engagement",
  "Corporate",
];

export const defaultGalleryItems = [
  { id: "wedding-1", image: "/images/gallery/wedding-1.jpg", title: "Royal Wedding", category: "Wedding", alt: "Royal wedding decor", published: true },
  { id: "wedding-2", image: "/images/gallery/wedding-2.jpg", title: "Wedding Celebration", category: "Wedding", alt: "Wedding celebration decor", published: true },
  { id: "wedding-3", image: "/images/gallery/wedding-3.jpg", title: "Wedding Celebration", category: "Wedding", alt: "Wedding celebration decor", published: true },
  { id: "wedding-10", image: "/images/gallery/wedding-10.jpg", title: "Wedding Celebration", category: "Wedding", alt: "Wedding celebration decor", published: true },
  { id: "wedding-11", image: "/images/gallery/wedding-11.jpg", title: "Wedding Celebration", category: "Wedding", alt: "Wedding celebration decor", published: true },
  { id: "mehndi-1", image: "/images/gallery/mehndi-1.jpg", title: "Mehndi Celebration", category: "Wedding", alt: "Mehndi celebration decor", published: true },
  { id: "mehndi-2", image: "/images/gallery/mehndi-2.jpg", title: "Mehndi Celebration", category: "Wedding", alt: "Mehndi celebration decor", published: true },
  { id: "mehndi-3", image: "/images/gallery/mehndi-3.jpg", title: "Mehndi Celebration", category: "Wedding", alt: "Mehndi celebration decor", published: true },
  { id: "haldi-1", image: "/images/gallery/haldi-1.jpg", title: "Haldi Celebration", category: "Wedding", alt: "Haldi celebration decor", published: true },
  { id: "haldi-2", image: "/images/gallery/haldi-2.jpg", title: "Haldi Celebration", category: "Wedding", alt: "Haldi celebration decor", published: true },
  { id: "mehndi-4", image: "/images/gallery/mehndi-4.jpg", title: "Mehndi Celebration", category: "Wedding", alt: "Mehndi celebration decor", published: true },
  { id: "wedding-gate", image: "/images/gallery/wedding_gate.jpg", title: "Wedding Entrance", category: "Wedding", alt: "Wedding entrance decor", published: true },
  { id: "wedding-4", image: "/images/gallery/wedding-4.jpg", title: "Wedding Celebration", category: "Wedding", alt: "Wedding celebration decor", published: true },
  { id: "birthday-1", image: "/images/gallery/birthday/birthday-1.jpg", title: "Birthday Celebration", category: "Birthday", alt: "Birthday celebration decor", published: true },
  { id: "birthday-2", image: "/images/gallery/birthday/birthday-2.jpg", title: "Birthday Celebration", category: "Birthday", alt: "Birthday celebration decor", published: true },
  { id: "birthday-3", image: "/images/gallery/birthday/birthday-3.jpg", title: "Luxury Birthday", category: "Birthday", alt: "Luxury birthday decor", published: true },
  { id: "birthday-4", image: "/images/gallery/birthday/birthday-4.jpg", title: "Luxury Birthday", category: "Birthday", alt: "Luxury birthday decor", published: true },
  { id: "birthday-5", image: "/images/gallery/birthday/birthday-5.jpg", title: "Luxury Birthday", category: "Birthday", alt: "Luxury birthday decor", published: true },
  { id: "birthday-6", image: "/images/gallery/birthday/birthday-6.jpg", title: "Luxury Birthday", category: "Birthday", alt: "Luxury birthday decor", published: true },
  { id: "reception-1", image: "/images/gallery/reception/reception-1.jpg", title: "Royal Reception", category: "Reception", alt: "Royal reception decor", published: true },
  { id: "corporate-1", image: "/images/gallery/corporate/corporate-1.jpg", title: "Corporate Event", category: "Corporate", alt: "Corporate event setup", published: true },
  { id: "corporate-3", image: "/images/gallery/corporate/corporate-3.jpg", title: "Corporate Event", category: "Corporate", alt: "Corporate event setup", published: true },
  { id: "corporate-4", image: "/images/gallery/corporate/corporate-4.jpg", title: "Corporate Experience", category: "Corporate", alt: "Corporate event experience", published: true },
  { id: "corporate-5", image: "/images/gallery/corporate/corporate-5.jpg", title: "Corporate Event", category: "Corporate", alt: "Corporate event setup", published: true },
  { id: "corporate-6", image: "/images/gallery/corporate/corporate-6.jpg", title: "Corporate Experience", category: "Corporate", alt: "Corporate event experience", published: true },
  { id: "corporate-7", image: "/images/gallery/corporate/corporate-7.jpg", title: "Corporate Event", category: "Corporate", alt: "Corporate event setup", published: true },
  { id: "corporate-8", image: "/images/gallery/corporate/corporate-8.jpg", title: "Corporate Experience", category: "Corporate", alt: "Corporate event experience", published: true },
  { id: "corporate-9", image: "/images/gallery/corporate/corporate-9.jpg", title: "Corporate Event", category: "Corporate", alt: "Corporate event setup", published: true },
  { id: "corporate-10", image: "/images/gallery/corporate/corporate-10.jpg", title: "Corporate Experience", category: "Corporate", alt: "Corporate event experience", published: true },
  { id: "corporate-11", image: "/images/gallery/corporate/corporate-11.jpg", title: "Corporate Event", category: "Corporate", alt: "Corporate event setup", published: true },
];
